### ISSUE TITLE
How does it compare to built_value?

### ISSUE THREAD

**Issue by kaciula** [jarekb123/dart_dataclass#3]
Hi.

The package looks useful and simple. I am wondering how it compares to built_value. Basically, I want to replace built_value with this package and the class properties be all final. This way I can have immutable classes with equals and copyWith. And with less code than with built_value.

Am I missing something? Are there any thing to consider? I suppose I have to continue using BuiltList instead of List right?

Thanks.

**Comment by jarekb123** [comment]
If you want to have immutable Lists you have to use some other implementation. Eg. from kt_dart or your mentioned BuiltList

**Comment by kaciula** [comment]
@jarekb123 Thanks for the answer. What I explicitly wanted to know is what is the difference between this library and built_value. How come this library has less boilerplate? Are there some specific features that are missing from this one compared to built_value?

**Comment by jarekb123** [comment]
This library focus on generating simple data class methods. There is no checks, no serialization and won't be.

BuiltValue generates code for classes which implements BuiltValue interface. BuiltValue provides also runtime null checks for non-nullable values. BuiltValue also provides json serialization.
